/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-08-07 07:10:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/global/resources_header.jsp", Long.valueOf(1564982880000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-outliers/webapps/outliers/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1563953904000L));
    _jspx_dependants.put("/WEB-INF/views/global/resources_body.jsp", Long.valueOf(1564982912000L));
    _jspx_dependants.put("/WEB-INF/views/global/nav_map.jsp", Long.valueOf(1565106882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- global resources -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/outliers/resources/bootstrap/4.3.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"resources/css/map.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Blindspot Finder - Ananlysis</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- hidden component -->\r\n");
      out.write("  <div id=\"loading\">\r\n");
      out.write("    <img src=\"resources/images/sandglass-time-loading-gif.svg\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("  <img src=\"\" id=\"imgOverlay\" />\r\n");
      out.write("  \r\n");
      out.write("  <!-- nav -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <nav class=\"navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("    <a class=\"navbar-brand col-sm-3 col-md-2 mr-0\" href=\"/outliers\">Blindspot Finder</a>\r\n");
      out.write("\r\n");
      out.write("    <form id=\"searchPlaces\" class=\"form-control form-control-dark w-100 align-items-center\" style=\"padding:0px;\">\r\n");
      out.write("\t    <input  type=\"text\" value=\"강남 경찰서\" \r\n");
      out.write("\t    placeholder=\"경찰서 입력\" aria-label=\"Search\" id=\"keyword\" style=\"width:100%; height: 100%;\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">\r\n");
      out.write("        <div class=\"sidebar-sticky\">\r\n");
      out.write("          <h5 class=\" d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("            <span>ADVANCED</span>\r\n");
      out.write("            <a class=\"d-flex align-items-center text-muted\" href=\"#\">\r\n");
      out.write("              <span data-feather=\"plus-circle\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </h5>\r\n");
      out.write("          <h4 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted orange-tooltip\">\r\n");
      out.write("            <span>Opacity</span>\r\n");
      out.write("          </h4>\r\n");
      out.write("          <ul class=\"nav flex-column\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"분석 오버레이의 투명도\">\r\n");
      out.write("            <li class=\"nav-item talign-ct\">\r\n");
      out.write("              <input type=\"text\" class=\"span2\" value=\"\" data-slider-min=\"0\" data-slider-max=\"0.8\" data-slider-step=\"0.1\" data-slider-value=\"0.4\" data-slider-id=\"adv-opacity\" id=\"adv-op\" data-slider-tooltip=\"show\" data-slider-handle=\"round\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <h4 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("            <span>Influence</span>\r\n");
      out.write("          </h4>\r\n");
      out.write("          <ul class=\"nav flex-column\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"방범시설의 영향력\">\r\n");
      out.write("            <li class=\"nav-item talign-ct\">\r\n");
      out.write("              <input type=\"text\" class=\"span2\" value=\"\" data-slider-min=\"0.5\" data-slider-max=\"1.5\" data-slider-step=\"0.1\" data-slider-value=\"1\" data-slider-id=\"adv-influence\" id=\"adv-inf\" data-slider-tooltip=\"hide\" data-slider-handle=\"round\" />\r\n");
      out.write("              <br><small class=\"text-muted\">다음 번 분석부터 적용됩니다.</small>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <h5 class=\" d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("            <span>ADDITIONAL</span>\r\n");
      out.write("          </h5>\r\n");
      out.write("          <h4 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("            <span>Tools</span>\r\n");
      out.write("          </h4>\r\n");
      out.write("          <ul class=\"nav flex-column\">\r\n");
      out.write("            <li class=\"nav-item talign-ct\">\r\n");
      out.write("              <div class=\"card\" style=\"width:85%; margin:auto;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\">Drawing</h5>\r\n");
      out.write("                  <h6 class=\"card-subtitle mb-2 text-muted\">polygons</h6>\r\n");
      out.write("                  <p class=\"card-text\"><small class=\"text-muted\">분석 오버레이가 표시중 일 때는 지도 조작이 불가능하므로, 그리기 툴을 이용하여 자세히 살펴볼 지역을 체크해 두세요.</small></p>\r\n");
      out.write("                  <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary btn-sm mr-2\" id=\"btnDraw\"><small>그리기</small></button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-warning btn-sm\" id=\"btnErase\"><small>지우기</small></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("  \r\n");
      out.write("      <main role=\"main\" class=\"col-md-10 ml-sm-auto col-lg-10 px-4\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom\">\r\n");
      out.write("          <h1 class=\"h2\">Dashboard</h1>\r\n");
      out.write("    \t  <div class=\"map-control\">\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  \t<button type=\"button\" class=\"btn btn-primary mr-2 active\" data-toggle=\"button\" aria-pressed=\"false\" autocomplete=\"off\" id=\"btnSpot\">\r\n");
      out.write("\t\t\t  방범시설\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("          \t<button type=\"button\" class=\"btn btn-danger btn-group-toggle mr-2\" data-container=\"body\" data-toggle=\"buttons\" \r\n");
      out.write("          \t\tdata-placement=\"top\" data-content=\"분석 오버레이 표시 중에는 지도를 조작할 수 없습니다.\" id=\"btnAnalysis\">\r\n");
      out.write("\t\t\t  \t사각지대 분석\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("          \r\n");
      out.write("          \t<div class=\"btn-group mr-2 btn-group-toggle btn-group-sm cstm_btn-md-ko\" data-toggle=\"buttons\" id=\"map_type_base\">\r\n");
      out.write("\t\t\t  <label class=\"btn btn-info active\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" autocomplete=\"off\" checked> 지도\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t  <label class=\"btn btn-info\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" autocomplete=\"off\"> 스카이뷰\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"btn-group mr-2 btn-group-toggle btn-group-sm cstm_btn-md-ko\" data-toggle=\"buttons\" id=\"map_type_overlay\">\r\n");
      out.write("\t\t\t  <label class=\"btn btn-secondary active\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" id=\"\" autocomplete=\"off\" checked> 없음\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t  <label class=\"btn btn-secondary\" id=\"btnRoadView\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" autocomplete=\"off\"> 도로\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t  <label class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" autocomplete=\"off\"> 교통량\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t  <label class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"options\" autocomplete=\"off\"> 지역구분\r\n");
      out.write("\t\t\t  </label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("   \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("  \t\t<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("\t\t  <i class=\"fas fa-ban\"></i>\r\n");
      out.write("\t\t   축척이 너무 높아 CCTV 표시가 제한되었습니다.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("         \r\n");
      out.write("          <!-- map -->\r\n");
      out.write("          <div class=\"map_wrap\" style=\"\">\r\n");
      out.write("            <div class=\"my-4 w-100\" id=\"map\" style=\"width:100%; height:95%; position:relative; overflow:hidden; z-index: 2\">\r\n");
      out.write("              <input data-toggle=\"button\" id=\"polygonbtn\" type=\"button\" value=\"구 자세히보기\" style=\"float:right;background-color:white;\r\n");
      out.write("           \t\tOpacity: 0.6;color:black;z-index:2;z-index: 2; position: relative;strokeColor:'#fff';strokeOpacity: 0.1;margin-top: 15px;\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu_wrap\" class=\"bg_white\" style=\"visibility:collapse;z-index:2\">\r\n");
      out.write("              <div class=\"option\"></div>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <ul id=\"placesList\"></ul>\r\n");
      out.write("              <div id=\"pagination\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        \t\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col align-self-start\">\r\n");
      out.write("    \t\t  <div class=\"card mb-2\">\r\n");
      out.write("                <div class=\"row no-gutters\">\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <img src=\"resources/images/police-station.png\" class=\"card-img\" alt=\"...\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5 class=\"card-title\">경찰서/파출소/지구대</h5>\r\n");
      out.write("                      <p class=\"card-text h3\" id=\"station-cnt\">-</p>\r\n");
      out.write("                      <p class=\"card-text\"><small class=\"text-muted\">현재 지도에 표시된 유인 방범시설 갯수</small></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col align-self-end\">\r\n");
      out.write("              <div class=\"card mb-2\">\r\n");
      out.write("                <div class=\"row no-gutters\">\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <img src=\"resources/images/cctv3.png\" class=\"card-img\" alt=\"...\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5 class=\"card-title\">폐쇄회로 텔레비전</h5>\r\n");
      out.write("                      <p class=\"card-text h3\" id=\"cctv-cnt\">-</p>\r\n");
      out.write("                      <p class=\"card-text\"><small class=\"text-muted\">현재 지도에 표시된 CCTV 갯수</small></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \t    </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("              <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">로드뷰</h5>\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                 <div class=\"container\">\r\n");
      out.write("                    <div id=\"roadview\" style=\"width:100%; height:350px;\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("      </main>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- global resources -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("  <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/outliers/resources/third-party-etc/popper.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/outliers/resources/bootstrap/4.3.1/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/bootstrap-slider.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- current resources -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/util.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/map.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=e4c097578c3266be7fa0ea7907486d92&libraries=services,drawing\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
