# Generated by Django 2.2.7 on 2019-11-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
