# Generated by Django 2.2.7 on 2019-11-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20191126_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
