# Generated by Django 2.2.6 on 2019-11-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.CharField(max_length=10)),
                ('bread', models.CharField(max_length=10)),
                ('vegetable', models.CharField(max_length=30)),
                ('sauce', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
