from editor import db
import datetime

date = datetime.datetime.now()
class Html(db.Model):
    __tablename__ =  "daebakProduct"
    #__table_args__ = {'mysql_collate': 'utf8mb4'}
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    handle = db.Column(db.String(100), nullable=False)
    title = db.Column(db.String(256), nullable=False)
    body_HTML = db.Column(db.Text, nullable=False)
    vendor = db.Column(db.String(100), nullable=False)
    type = db.Column(db.String(100), nullable=False)
    tags = db.Column(db.Text, nullable=False)
    published = db.Column(db.String(100), nullable=False)
    option1_name = db.Column(db.String(100), nullable=False)
    option1_value = db.Column(db.String(100), nullable=False)
    option2_name = db.Column(db.String(100), nullable=False)
    option2_value = db.Column(db.String(100), nullable=False)
    option3_name = db.Column(db.String(100), nullable=False)
    option3_value = db.Column(db.String(100), nullable=False)
    variant_sku = db.Column(db.String(256), nullable=False)
    variant_grams = db.Column(db.String(100), nullable=False)
    variant_inventory_tracker = db.Column(db.String(100), nullable=False)
    variant_inventory_qty = db.Column(db.String(100), nullable=False)
    variant_inventory_policy = db.Column(db.String(100), nullable=False)
    variant_fullfillment_service = db.Column(db.String(100), nullable=False)
    varient_price = db.Column(db.String(100), nullable=False)
    variant_compare_at_price = db.Column(db.String(100), nullable=False)
    varient_requires_shipping = db.Column(db.String(100), nullable=False)
    variant_taxable= db.Column(db.String(100), nullable=False)
    variant_barcord = db.Column(db.String(100), nullable=False)
    imgage_src = db.Column(db.String(256), nullable=False)
    image_position = db.Column(db.String(100), nullable=False)
    image_alt_text = db.Column(db.String(100), nullable=False)
    gift_card = db.Column(db.String(100), nullable=False)
    seo_title= db.Column(db.String(100), nullable=False)
    seo_description = db.Column(db.String(100), nullable=False)
    google_shopping_google_product_category = db.Column(db.String(100), nullable=False)
    google_shopping_gender = db.Column(db.String(100), nullable=False)
    goggle_shopping_age_group = db.Column(db.String(100), nullable=False)
    google_shopping_mpn = db.Column(db.String(100), nullable=False)
    google_shopping_adwords_grouping = db.Column(db.String(100), nullable=False)
    google_shopping_adwords_labels = db.Column(db.String(100), nullable=False)
    google_shopping_condition = db.Column(db.String(100), nullable=False)
    google_shopping_custom_product = db.Column(db.String(100), nullable=False)
    google_shopping_custion_label0 = db.Column(db.String(100), nullable=False)
    google_shopping_custion_label1 = db.Column(db.String(100), nullable=False)
    google_shopping_custion_label2 = db.Column(db.String(100), nullable=False)
    google_shopping_custion_label3 = db.Column(db.String(100), nullable=False)
    google_shopping_custion_label4 = db.Column(db.String(100), nullable=False)
    variant_image = db.Column(db.String(100), nullable=False)
    variant_weight_unit = db.Column(db.String(100), nullable=False)
    variant_tax_code = db.Column(db.String(100), nullable=False)
    cost_per_item = db.Column(db.String(100), nullable=False)
    def __repr__(self):
        return '<Html %r>' % self.handle