# Generated by Django 2.2.10 on 2020-05-20 14:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0002_keyword_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='high_word_frequency',
            field=jsonfield.fields.JSONField(default={}, dump_kwargs={'ensure_ascii': False}),
        ),
    ]
