"""empty message

Revision ID: 18d512bf2fe4
Revises: 320480ebd513
Create Date: 2020-07-21 14:18:34.879358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d512bf2fe4'
down_revision = '320480ebd513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'user_id')
    # ### end Alembic commands ###
