# Generated by Django 2.2.7 on 2019-11-20 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77)),
                ('title_en', models.CharField(max_length=77)),
                ('audience', models.IntegerField(default=0)),
                ('open_date', models.DateField(default=datetime.date.today)),
                ('genre', models.CharField(max_length=77)),
                ('watch_grade', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('post', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
