# Generated by Django 2.2.7 on 2019-11-14 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_delete_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('datetime', models.DateField(default=datetime.date.today)),
                ('sandwitch', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('bread', models.CharField(max_length=20)),
                ('check', models.CharField(max_length=20)),
            ],
        ),
    ]
