# Generated by Django 2.2.7 on 2019-11-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
