# Generated by Django 2.2.7 on 2019-11-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
