# Generated by Django 3.1.6 on 2021-02-18 18:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('high_word_frequency', jsonfield.fields.JSONField(default={}, dump_kwargs={'ensure_ascii': False})),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
