# Generated by Django 2.2.7 on 2019-11-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_subway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
