# Generated by Django 2.2.7 on 2019-11-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_subway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
