# Generated by Django 2.2.7 on 2019-11-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
